### ISSUE TITLE
python-dateutil is locked to v2.2

### ISSUE THREAD

**Issue by ktdreyer** [Tendrl/common#63]
`requirements.txt` currently contains `python-dateutil==2.2`

Would you please loosen this version requirement, or drop the number altogether?

RHEL/CentOS 7 base has python-dateutil-1.5, and [Ubuntu Xenial has python-dateutil 2.4.2](http://packages.ubuntu.com/xenial/python-dateutil).

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/common/commit/71d5edde44e6e1df5b1a12562c0f348f3af13c3d
