### ISSUE TITLE
Travis job should check git commit message for github bug id and an optional tendrl spec name

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/common#66]
Moving on, all git commits  should contain mandatory mention on newline of 
"tendrl-bug-id: <tendrl_repo>/\<github-issue-id>" and optional mention of "tendrl-spec: <tendrl_spec_name>" in the commit msg.

eg: 
"""
Packaging python-etcd

Added Makefile and spec file to create python-etcd package
Now one can use "make rpm" to pull the latest source from github
and build the source rpm
and using the Makefile one can also build rpm using "make rpm"
which will use mock to build the rpm using srpm.

tendrl-bug-id: Tendrl/common#18

tendrl-spec: refactor_gluster_integration_get_state_dump
"""

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/common/commit/af0c643b7944b4b54376b91a9cb7e12d435e7159

**Comment by r0h4n** [comment]
@brainfunked @nthomas-redhat @TimothyAsir @shtripat @GowthamShanmugam @nnDarshan @anivargi @anmolbabu  Please take note.and make appropriate changes to your repos

**Comment by nnDarshan** [comment]
@r0h4n adding a "#" before the issue number will automatically hyperlink the issue to the commit message. Is it better to have something like:
"tendrl-bug-id: <tendrl_repo>/#<github-issue-id>"

or just <repo-name>/<issue-no> will take care of it ?

**Comment by r0h4n** [comment]
@nnDarshan Thanks for suggesting, making that change
