### ISSUE TITLE
Add a way to decorate a class as java equivalent singleton

### ISSUE THREAD

**Issue by anmolbabu** [Tendrl/common#69]
Add a way to decorate a class as java equivalent singleton so that it is created only once thereby helping to avoid sometimes unnecessary redundant initialization.

**Comment by r0h4n** [comment]
Is this part of some spec?

**Comment by anmolbabu** [comment]
This does not feature in any spec as such but its used as part of https://github.com/Tendrl/performance_monitoring/pull/2/files#diff-e26326fd1f571ef4c0c2e0ca4afaf826
to create a time series db manager once based on configuration in conf file.I'll raise a spec for feature that uses this currently.
