### ISSUE TITLE
[rpm packaging] configuration files are not marked as configuration

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/common#72]
Package `tendrl-common-0.0.1-1.el7.centos.noarch` from `https://copr-be.cloud.fedoraproject.org/results/tendrl/tendrl/epel-7-x86_64/` copr doesn't mark configuration files as configuration.

This breaks Fedora packaging policy and will have inpact on user changes in
affected configuration files during package upgrades.

## Reproducer

```
# rpm -ql tendrl-common | grep ^/etc
/etc/tendrl
/etc/tendrl/common_logging.yaml
# rpm -qc tendrl-common 
#
```

While expected result would be:

```
# rpm -ql tendrl-common | grep ^/etc
/etc/tendrl
/etc/tendrl/common_logging.yaml
# rpm -qc tendrl-common 
/etc/tendrl/common_logging.yaml
#
```

## Additional information

[Fedora wikipage on rpm packaging](https://fedoraproject.org/wiki/How_to_create_an_RPM_package) states:

Configuration files should be placed in /etc and are normally specified like
this (which makes sure user changes aren't overwritten on update):

    %config(noreplace) %{_sysconfdir}/foo.conf

If the update uses a non-backwards-compatible configuration format, then
specify them like this:

    %config %{_sysconfdir}/foo.conf

You can also see additional description of [rpm and configuration files](http://www-uxsup.csx.cam.ac.uk/%7Ejw35/docs/rpm_config.html).

**Comment by mbukatov** [comment]
I could have provided suggested patch, if I knew where the official dist-git with tendrl-common spec file is hosted.

**Comment by nthomas-redhat** [comment]
@mbukatov, please push a patch upstream - https://github.com/Tendrl/common/blob/master/tendrl-common.spec

**Comment by mbukatov** [comment]
@nthomas-redhat Thanks, I will propose a fix there then. I was not sure if this spec file was used for the builds.

**Comment by mbukatov** [comment]
I did standard rebuild on fedora via mock:

```
$ python setup.py sdist
$ cp dist/tendrl-common-0.0.1.tar.gz /home/makerpm/rpmbuild/SOURCES
$ cp tendrl-common.spec /home/makerpm/rpmbuild/SPECS
$ cd /home/makerpm/rpmbuild/SPECS
$ rpmbuild -bs tendrl-common.spec
$ mock -r epel-7-x86_64 --rebuild /home/makerpm/rpmbuild/SRPMS/tendrl-common-0.0.1-2.fc24.src.rpm
```

Then:

```
$ cd /var/lib/mock/epel-7-x86_64/result
$ rpm -qc -p tendrl-common-0.0.1-2.el7.centos.noarch.rpm
/etc/tendrl/common_logging.yaml
```
