### ISSUE TITLE
[rpm packaging] [question] default config files in the package

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/common#74]
[Developer installation documentation](https://github.com/Tendrl/common/blob/c3495826f483d38603898287080aa23a4a2fc44e/doc/source/installation.rst) (admin/user centric documentation focusing on binary packages was not available when this issue was created)  explains `tendrl-common` configuration as follows:

```
# cp etc/tendrl/tendrl.conf.sample /etc/tendrl/tendrl.conf
# cp etc/sample/logging.yaml.timedrotation.sample /etc/tendrl/common_logging.conf
# vim /etc/tendrl/tendrl.conf # ... configure value of etcd_connection ...
```

While in the `tendrl-common-0.0.1-1.el7.centos.noarch` package, there is just `common_logging.conf` file packaged in `/etc/tendrl` directory:

```
# rpm -ql tendrl-common | grep ^/etc
/etc/tendrl
/etc/tendrl/common_logging.yaml
```

What is the reason for this? I'm just curious.

**Comment by nthomas-redhat** [comment]
@mbukatov , tendrl.conf is installed as part of tendrl-node-agent
rpm -ql tendrl-node-agent | grep ^/etc
/etc/tendrl/node_agent
/etc/tendrl/node_agent_logging.yaml
/etc/tendrl/tendrl.conf

**Comment by mbukatov** [comment]
This means that when one is installing `tendrl-common` either from rpm or pip packages, `tendrl.conf` should not be configured at all, as it would be configured later when `tendrl-node-agent` is installed, right?

**Comment by TimothyAsir** [comment]
yes

**Comment by mbukatov** [comment]
Thanks for the clarification. We just need to make sure that the same is stated in non development (from rpm packages, not from source) installation documentation later when such documentation is created.

**Comment by ktdreyer** [comment]
What bug tracks the task of writing user documentation to install from RPMs?

**Comment by mbukatov** [comment]
@ktdreyer there is neither such documentation nor bug to track work on it, I usually file a github issue for any particular problem or open question I stumble upon

IMHO it would make sense to cover installation from rpm packages from Tendrl project perspective, not on a level of individual packages, in `Tendrl/documentation` repository.

**Comment by mbukatov** [comment]
> What bug tracks the task of writing user documentation to install from RPMs?

Just for a record, such issue has been just created: https://github.com/Tendrl/documentation/issues/68 (see also my  https://github.com/Tendrl/documentation/issues/68#issuecomment-265993416 about priorities as I see it now)
